import * as Images from '@images';

export default {
  IMAGE_BASE_URL: 'https://careportal.curio-dtx.com/',
  BASE_URL: 'https://mean.stagingsdei.com:6047/',

  URL: {
    LOGIN: 'user/login',
    SIGNUP: 'user/register',
    CATEGORY: 'category/pagination?perPage=10&page=1',
    MERCHANT: 'merchant/pagination?perPage=',
    SUB_CATEGORY: 'subCategory/getSubCatId?id=',
    CATEGORY_DEATILS: 'subcategory/find?id=',
  },
  FONTS: {
    BOLD: 'Oswald-Bold',
    EXTRA_LIGHT: 'Oswald-ExtraLight',
    LIGHT: 'Oswald-Light',
    REGULAR: 'Oswald-Regular',
    SEMI_BOLD: 'Oswald-SemiBold',
    MEDIUM: 'Oswald-Medium',
    CIRCULAR_REGULAR: 'CircularStd-Book',
    CIRCULAR_MEDIUM: 'CircularStd-Medium',
    CIRCULAR_BOLD: 'CircularStd-Bold',
  },
  COLOR: {
    ICON_COLOR: '#0069B9',
    APP_COLOR: '#1769B5',
    COLOR_PRIMARY: '#1492E6',
    BUTTON_COLOR: '#0069B9',

    PRIMARY1: '#1B82D4',
    SECONDARY: '#6C8AEA',
    PRIMARY: '#6EC592',
    BACKGROUND: '#F7F7F7',
    TEXT_ORANGE: '#EF7E4B',
    BORDER_LIGHT: '#707070',
    WHITE: '#fff',
    GREY: '#676767' /* Font Regular */,
    DARKGREY: '#3D3D3D' /* Font Bold */,
    SHADOW: '#0000001A',
    GREEN: '#49D93F',
    CERULEAN: '#1499D6',
    CINNABAR: '#EC3737',
    BLACK: '#000000',
    ERROR: '#d83b3b',
    CALENDAR_DISABLE: '#AAAAAA',
    EMPTY: '#F8F8F8',
    TABLET: '#F7D547',
    TRANSPARENT: 'transparent',
    BACKGROUND_ORANGE: '#F05A28'
  },
  STRINGS: {
    SIGNIN: 'Sign In',
    SIGNUP: 'Sign Up',
    EMAILADDR: 'Email Address',
    EMAILPASWD: 'Enter Password',
    EMAILHOLDER: 'johndoe@email.com',
    TAKEDOSE: 'Take your next dose on time',
    TRY_AGAIN: 'Something went wrong. Please try again !',
    TIMEOUT_ERROR: 'Request timed out. Network Error',
    EMAIL_ERROR: 'Email address is invalid!',
    // PASSWORD_ERROR:
    //   'Password should be minimum 8 character length, atleast 1 special character and 1 digit',
    PASSWORD_ERROR: "Password should be 6 digit with one capital, small and special charater.",
    VALID_ERROR: 'Please enter valid email and password',
    CHECK_NETWORK: 'Please check your internet connection',

    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    ROLE: 'Role',
    PHONE: 'Phone Number',
    ADDRESS: 'Address',
    CITY: 'City',
    STATE: 'State',
    COUNTRY: 'Country',
    ZIP: 'Zip code',
  },
  SCREENS: {
    AUTH: 'Auth',
    SIGNIN: 'SignIn',
    REGISTER: 'Register',
    DASHBOARD: 'DashBoard',
  },
  TABS: [
    { id: 0, title: 'Next Dosage', logo: Images.Dosage },
    { id: 1, title: 'Assessments', logo: Images.Assessments },
    { id: 2, title: 'Care Team', logo: Images.CareTeam },
    { id: 3, title: 'Schedule', logo: Images.Schedule },
    { id: 4, title: 'Sync Data', logo: Images.Sync },
    { id: 5, title: 'Reminders', logo: Images.Reminders },
    { id: 6, title: 'Points', logo: Images.Points },
    { id: 7, title: 'CBT', logo: Images.Info },
  ],

  ACTION_TYPE: {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_RESET: 'LOGIN_RESET',

    LOGOUT: 'LOGOUT',

    SIGNUP_REQUEST: 'GET_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'GET_SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'GET_SIGNUP_FAIL',

    GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAIL: 'GET_CATEGORY_FAIL',

    GET_MERCHANT_REQUEST: 'GET_MERCHANT_REQUEST',
    GET_MERCHANT_SUCCESS: 'GET_MERCHANT_SUCCESS',
    GET_MERCHANT_FAIL: 'GET_MERCHANT_FAIL',

    GET_SUB_CATEGORY_REQUEST: 'GET_SUB_CATEGORY_REQUEST',
    GET_SUB_CATEGORY_SUCCESS: 'GET_SUB_CATEGORY_SUCCESS',
    GET_SUB_CATEGORY_FAIL: 'GET_SUB_CATEGORY_FAIL',

    GET_CATEGORY_DETAILS_REQUEST: 'GET_CATEGORY_DETAILS_REQUEST',
    GET_CATEGORY_DEATAILS_SUCCESS: 'GET_CATEGORY_DEATAILS_SUCCESS',
    GET_CATEGORY_DETAILS_FAIL: 'GET_CATEGORY_DETAILS_FAIL',
  },
};
